import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { PrimaryButton, Screen, ScreenHeader, SecondaryButton } from '@/components/roxstar-ui';
import { Palette } from '@/constants/theme';
import { getSpin } from '@/services/spinService';
import { getRoom } from '@/services/roomService';
import { connectSocket, joinRoomSocket, startSpinSocket, subscribeRoom } from '@/services/socketService';
import { useSpinStore } from '@/stores/spin';
import type { RoomState } from '@/types/room';

export default function SpinScreen() {
  const router = useRouter(); const { roomId, userId } = useLocalSearchParams<{ roomId: string; userId: string }>(); const [room, setRoom] = useState<RoomState | null>(null); const [error, setError] = useState(''); const spinState = useSpinStore((store) => store.state); const beginStarting = useSpinStore((store) => store.beginStarting); const applyStarted = useSpinStore((store) => store.applyStarted); const applyElimination = useSpinStore((store) => store.applyElimination); const applyWinner = useSpinStore((store) => store.applyWinner); const applySnapshot = useSpinStore((store) => store.applySnapshot); const abort = useSpinStore((store) => store.abort); const reset = useSpinStore((store) => store.reset);
  const reload = () => { if (!roomId) return; void Promise.all([getRoom(roomId), getSpin(roomId)]).then(([nextRoom, nextSpin]) => { setRoom(nextRoom); applySnapshot(nextSpin); }).catch(() => undefined); };
  useEffect(() => { if (!roomId || !userId) return; connectSocket(); joinRoomSocket(roomId, userId); reload(); return subscribeRoom({ spin_started: (payload) => applyStarted(payload.eligibleParticipants), user_eliminated: (payload) => applyElimination(payload.userId), winner_announced: (payload) => applyWinner({ userId: payload.winnerId, username: payload.username, status: 'winner' }), spin_error: (payload) => { const message = payload.message.toLowerCase(); const friendly = message.includes('owner') ? 'Only the room owner can start a spin' : message.includes('member') || message.includes('participant') ? 'Need 3-20 connected players to start' : message.includes('running') || message.includes('available') ? 'A spin is already in progress' : payload.message; abort(friendly); setError(friendly); } }); }, [roomId, userId, applyStarted, applyElimination, applyWinner, applySnapshot, abort]);
  const connectedCount = room?.members.filter((member) => member.isConnected !== false).length ?? 0;
  const isOwner = room?.ownerId === userId;
  const canStart = Boolean(isOwner && connectedCount >= 3 && connectedCount <= 20 && (spinState.status === 'waiting' || spinState.status === 'aborted'));
  const start = () => { if (!roomId || !userId || !isOwner || connectedCount < 3 || connectedCount > 20 || spinState.status === 'starting' || spinState.status === 'running' || spinState.status === 'completed') return; setError(''); beginStarting(); startSpinSocket(roomId, userId); };
  const participants = spinState.status === 'running' ? spinState.participants : [];
  const winner = spinState.status === 'completed' ? spinState.winner : null;
  return <Screen><ScreenHeader title="Spin" subtitle={spinState.status === 'running' ? 'Server-controlled elimination in progress' : 'The server controls every elimination'} onBack={() => router.back()} />{error ? <View style={styles.snackbar}><Text style={styles.snackbarText}>{error}</Text></View> : null}{winner ? <View style={styles.winner}><Text style={styles.winnerLabel}>WINNER</Text><Text style={styles.winnerName}>{winner.username}</Text></View> : null}<Text style={styles.count}>Connected players: {connectedCount}</Text>{isOwner && (spinState.status === 'waiting' || spinState.status === 'aborted') ? <View style={styles.startSection}><PrimaryButton label={canStart ? 'Start server spin' : 'Start server spin'} icon="play-arrow" onPress={start} /><Text style={styles.hint}>{connectedCount < 3 || connectedCount > 20 ? `Need 3-20 players, currently ${connectedCount}` : 'The server will validate the room again.'}</Text></View> : null}{spinState.status === 'starting' ? <Text style={styles.live}>Starting spin…</Text> : null}{spinState.status === 'running' ? <View><Text style={styles.live}>{participants.filter((participant) => participant.status === 'active').length} active players</Text>{participants.map((participant) => <View key={participant.userId} style={[styles.participant, participant.status === 'eliminated' && styles.eliminated]}><Text style={[styles.participantName, participant.status === 'eliminated' && styles.struck]}>{participant.username}</Text><Text style={styles.participantStatus}>{participant.status === 'eliminated' ? 'ELIMINATED' : 'ACTIVE'}</Text></View>)}<Text style={styles.feedTitle}>Elimination feed</Text>{spinState.eliminatedSoFar.map((participant) => <Text key={participant.userId} style={styles.feedLine}>{participant.username} was eliminated</Text>)}</View> : null}{spinState.status === 'completed' ? <SecondaryButton label="Reset for a new spin" icon="refresh" onPress={() => { reset(); setError(''); }} /> : null}{spinState.status === 'aborted' && !error ? <Text style={styles.error}>{spinState.reason}</Text> : null}</Screen>;
}
const styles = StyleSheet.create({ snackbar: { backgroundColor: Palette.danger, borderRadius: 10, padding: 12, marginBottom: 14 }, snackbarText: { color: '#FFFFFF', fontWeight: '700' }, winner: { backgroundColor: Palette.gold, borderRadius: 16, padding: 20, marginBottom: 18 }, winnerLabel: { color: Palette.background, fontSize: 12, fontWeight: '900', letterSpacing: 1.2 }, winnerName: { color: Palette.background, fontSize: 30, fontWeight: '900', marginTop: 4 }, count: { color: Palette.text, fontWeight: '800', marginBottom: 12 }, startSection: { marginBottom: 18 }, hint: { color: Palette.muted, textAlign: 'center', marginTop: 9, fontSize: 12 }, live: { color: Palette.muted, fontWeight: '700', marginVertical: 14 }, participant: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Palette.border, paddingVertical: 13 }, eliminated: { opacity: 0.5 }, participantName: { color: Palette.text, fontSize: 16, fontWeight: '700' }, struck: { textDecorationLine: 'line-through' }, participantStatus: { color: Palette.muted, fontSize: 10, fontWeight: '900' }, feedTitle: { color: Palette.text, fontWeight: '800', marginTop: 22, marginBottom: 8 }, feedLine: { color: Palette.muted, paddingVertical: 4 }, error: { color: Palette.danger } });
