import { useRouter } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { PrimaryButton, Screen, ScreenHeader, SecondaryButton } from '@/components/roxstar-ui';
import { Palette } from '@/constants/theme';
import { createRoom, joinRoom } from '@/services/roomService';
import { useAuthStore } from '@/stores/auth';

export default function RoomsScreen() {
  const router = useRouter(); const user = useAuthStore((s) => s.user); const setIdentity = useAuthStore((s) => s.setIdentity); const [username, setUsername] = useState(user?.name ?? ''); const [deviceId, setDeviceId] = useState(user?.deviceId ?? ''); const [code, setCode] = useState(''); const [working, setWorking] = useState(false); const [error, setError] = useState('');
  const identity = () => ({ username: username.trim(), deviceId: deviceId.trim() });
  const open = (entry: { roomId?: string; id?: string; roomCode: string; userId: string }) => router.push({ pathname: '/room', params: { roomId: entry.roomId ?? entry.id ?? '', roomCode: entry.roomCode, userId: entry.userId } });
  const validateIdentity = () => { if (!username.trim() || !deviceId.trim()) { setError('Enter both username and device ID.'); return false; } setIdentity(username.trim(), deviceId.trim()); return true; };
  const create = async () => { if (!validateIdentity()) return; setWorking(true); setError(''); try { open(await createRoom(identity())); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create room. Check that the backend is running on port 4000.'); } finally { setWorking(false); } };
  const join = async () => { if (!validateIdentity()) return; if (code.trim().length !== 6) { setError('Enter the 6-character room code.'); return; } setWorking(true); setError(''); try { open(await joinRoom(code.trim(), identity())); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to join room. Check that the backend is running on port 4000.'); } finally { setWorking(false); } };
  return <Screen><ScreenHeader title="Rooms" subtitle="Start a live voice spin" /><View style={styles.identity}><Text style={styles.formTitle}>Your backend identity</Text><Text style={styles.formNote}>These values are sent to the backend when you create or join a room.</Text><TextInput autoCapitalize="none" value={username} onChangeText={(value) => { setUsername(value); setError(''); }} placeholder="Username" placeholderTextColor={Palette.muted} style={styles.formInput} /><TextInput autoCapitalize="none" value={deviceId} onChangeText={(value) => { setDeviceId(value); setError(''); }} placeholder="Device ID" placeholderTextColor={Palette.muted} style={styles.formInput} /></View><View style={styles.feature}><Text style={styles.eyebrow}>HOST A SESSION</Text><Text style={styles.featureTitle}>Make tonight interesting.</Text><Text style={styles.featureText}>Invite 3–20 people, then start a server-controlled elimination round.</Text><PrimaryButton label={working ? 'Creating…' : 'Create a room'} icon="add" onPress={() => void create()} /></View><View style={styles.or}><View style={styles.line} /><Text style={styles.orText}>OR JOIN WITH A CODE</Text><View style={styles.line} /></View><TextInput autoCapitalize="characters" maxLength={6} value={code} onChangeText={(v) => { setCode(v.replace(/[^a-z0-9]/gi, '').toUpperCase()); setError(''); }} placeholder="ABC123" placeholderTextColor={Palette.muted} style={styles.input} /><SecondaryButton label={working ? 'Joining…' : 'Join room'} icon="login" onPress={() => void join()} />{error ? <Text style={styles.error}>{error}</Text> : null}</Screen>;
}
const styles = StyleSheet.create({ identity: { backgroundColor: Palette.surface, borderColor: Palette.border, borderWidth: 1, borderRadius: 16, padding: 16, marginBottom: 16 }, formTitle: { color: Palette.text, fontSize: 16, fontWeight: '800' }, formNote: { color: Palette.muted, fontSize: 12, lineHeight: 18, marginTop: 5, marginBottom: 12 }, formInput: { height: 48, backgroundColor: Palette.background, borderRadius: 12, borderWidth: 1, borderColor: Palette.border, color: Palette.text, paddingHorizontal: 14, marginTop: 8 }, feature: { backgroundColor: Palette.accentSoft, borderColor: '#6042A5', borderWidth: 1, borderRadius: 24, padding: 22 }, eyebrow: { color: Palette.pink, fontSize: 11, fontWeight: '900', letterSpacing: 1.2 }, featureTitle: { color: Palette.text, fontSize: 26, fontWeight: '900', marginTop: 8 }, featureText: { color: Palette.muted, fontSize: 14, lineHeight: 21, marginTop: 8, marginBottom: 20 }, or: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 28 }, line: { flex: 1, height: 1, backgroundColor: Palette.border }, orText: { color: Palette.muted, fontSize: 10, fontWeight: '800', letterSpacing: .8 }, input: { height: 56, backgroundColor: Palette.surface, borderRadius: 14, borderWidth: 1, borderColor: Palette.border, color: Palette.text, paddingHorizontal: 16, fontWeight: '800', fontSize: 20, letterSpacing: 3, marginBottom: 10 }, error: { color: Palette.danger, marginTop: 14 } });
